services:
  backend:
    image: dev-bloglist-backend
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    environment:
      - MONGO_URI=${MONGO_URI}
      - TEST_MONGO_URI=${TEST_MONGO_URI}
      - SECRET=${SECRET}
    volumes:
      - ./backend:/usr/src/app

  frontend:
    image: dev-bloglist-frontend
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    environment:
      - VITE_BACKEND_URL=/api/
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
  
  nginx:
    image: nginx
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - backend
      - frontend