name: Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - closed

jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      TEST_MONGO_URI: ${{ secrets.TEST_MONGO_URI }}
      SECRET: ${{ secrets.SECRET }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: ./build.sh
      - run: npm run test
      - name: Install playwright browsers
        run: npx playwright install --with-deps chromium firefox
      - run: npm run test:e2e

  deploy:
    needs: [test]
    runs-on: ubuntu-22.04
    if: >-
      ${{ 
        ((github.event_name == 'pull_request' 
        && github.event.pull_request.merged == true) 
        || (github.ref_name == 'main' && github.event_name == 'push')) 
        && !contains(github.event.commits.*.message, '#skip') 
      }}
    steps:
      - name: Deploy
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}

  tag_release:
    needs: [test, deploy]
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    if: ${{ needs.deploy.result != 'skipped' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: "0"
      - name: Bump and tag version number
        uses: anothrNick/github-tag-action@1.73.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
